### ISSUE TITLE
AI monitor should prefer the direction of tree

### ISSUE THREAD

**Issue by sugar700** [flarn2006/TPPSimulator#2]
> Spam Start and A to use Cut!
> (Also, a little up, down, and B.)

![](https://cloud.githubusercontent.com/assets/1297598/6426461/2b027da8-bf5c-11e4-8752-ad7652125437.png)

You know, in this case, Right looks like really helpful.

**Comment by flarn2006** [comment]
Yeah, I've noticed that; I'm planning on having it still use some of the path directions. Thanks though! I'll close this once I've done that.

**Comment by flarn2006** [comment]
Should be fixed in beta 2.
